'use client'
import { Provider } from "react-redux";
import Footer from "./components/Footer";
import Header from "./components/Header";
import "./globals.css";
import store from "@/store/store";

export default function RootLayout({ children }) {
  return (
    <html lang="en">

        <head>
            <title>BookCafe</title>
            <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
        </head>

      <body>
      <Provider store={store}>
        <Header/>
        {children}
        <Footer/>
      </Provider>
        </body>
    </html>
  );
}
