export const conf = {
    APPWRITE_URL:String(process.env.NEXT_PUBLIC_APPWRITE_URL),
    PROJECT_ID:String(process.env.NEXT_PUBLIC_PROJECT_ID),
    DATABASE_ID:String(process.env.NEXT_PUBLIC_DATABASE_ID),
    COLLECTION_ID_BOOKSTORE:String(process.env.NEXT_PUBLIC_COLLECTION_ID_BOOKSTORE),
    COLLECTION_ID_USERDETAILS:String(process.env.NEXT_PUBLIC_COLLECTION_ID_USERDETAILS),
    COLLECTION_ID_ORDERLIST:String(process.env.NEXT_PUBLIC_COLLECTION_ID_ORDERLIST),
    BUCKET_ID_IMG:String(process.env.NEXT_PUBLIC_BUCKET_ID_IMG),
    BUCKET_ID_USER:String(process.env.NEXT_PUBLIC_BUCKET_ID_USER),
    
    RAZORPAY_ID:String(process.env.NEXT_PUBLIC_RAZORPAY_ID),
    RAZORPAY_SECRET:String(process.env.NEXT_PUBLIC_RAZORPAY_SECRET),

    RAZORPAY_TEST_ID:String(process.env.NEXT_PUBLIC_RAZORPAY_TEST_ID),
    RAZORPAY_TEST_SECRET:String(process.env.NEXT_PUBLIC_RAZORPAY_TEST_SECRET),

    EMAILHOST:String(process.env.NEXT_PUBLIC_EMAILHOST),
    EMAILUSER:String(process.env.NEXT_PUBLIC_EMAILUSER),
    EMAILPASS:String(process.env.NEXT_PUBLIC_EMAILPASS),

}
