export const conf = {
    APPWRITE_URL:String(process.env.NEXT_PUBLIC_APPWRITE_URL),
    PROJECT_ID:String(process.env.NEXT_PUBLIC_PROJECT_ID),
    DATABASE_ID:String(process.env.NEXT_PUBLIC_DATABASE_ID),
    COLLECTION_ID_BOOKSTORE:String(process.env.NEXT_PUBLIC_COLLECTION_ID_BOOKSTORE),
    COLLECTION_ID_USERDETAILS:String(process.env.NEXT_PUBLIC_COLLECTION_ID_USERDETAILS),
    COLLECTION_ID_ORDERLIST:String(process.env.NEXT_PUBLIC_COLLECTION_ID_ORDERLIST),
    BUCKET_ID_IMG:String(process.env.NEXT_PUBLIC_BUCKET_ID_IMG),
    BUCKET_ID_USER:String(process.env.NEXT_PUBLIC_BUCKET_ID_USER),
}
